name: Continuous Deployment to EC2

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          /usr/bin/docker version || echo "Docker not found"
          sudo docker pull bandhan99/newz_shortie:${{ github.sha }}
          sudo docker stop shortie-container || true
          sudo docker rm shortie-container || true
          sudo docker run -d --name shortie-container -p 5000:5000 bandhan99/newz_shortie:${{ github.sha }}
        '
